apiVersion: authconfig.authorino.kuadrant.io/v1beta3
kind: AuthConfig
metadata:
  labels:
    app.kubernetes.io/name: authorino
    app.kubernetes.io/managed-by: kustomize
  name: authconfig-sample
spec:
  # TODO(user): Add fields here
